const mongoose=require('mongoose')
const itemSchema=mongoose.Schema(
    {
        titulo:{
            type:String,
            require:true,
            trim:true
        },
        tipo:{
            type:String,
            require:true,
            trim:true
        },
        genero:{
            type:String,
            require:true,
            trim:true
        },
        ano:{
            type:String,
            require:true,
            trim:true
        },
        duracion:{
            type:Number,
            require:true,
        },
        reparto:{
            type:Array,
        },
        created_at:{
            type: Date,
            default:Date.now()
        },
        created_by:{
            type:String,
            require:true,
            trim:true
        },
        imagen:{
            type:String,
            require:true
        },
        video:{
            type:String
        }
    }
)
module.exports=mongoose.model("item", itemSchema)